---
- name: Stop and Remove Docker Containers
  hosts: project_hosts
  become: yes
  vars:
    docker_image: "{{ image_name }}"  # Use the passed argument as the image name

  tasks:
    - name: Stop the Docker container
      ansible.builtin.docker_container:
        name: project
        state: stopped

    - name: Remove the Docker container
      ansible.builtin.docker_container:
        name: project
        state: absent

